
baseURI=https://reqres.in/api
apiKey=sk_test_QMENTISAI_abc1234567890
createUserEndpoint=/users
getUserEndpoint=/users/{id}
getUserWithQueryEndpoint=/users
getAllUsersEndpoint=/users
updateUserEndpoint=/users/{id}
deleteUserEndpoint=/users
